In [1]:
import torch

In [2]:
a = torch.tensor([1,2,3], dtype=torch.float32)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

tensor([1., 2., 3.])
torch.Size([3])
1
torch.float32


In [3]:
b = torch.rand([3,3,3], dtype=torch.float32)
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)

tensor([[[0.2197, 0.1127, 0.8237],
         [0.0028, 0.5778, 0.9736],
         [0.2440, 0.7139, 0.0444]],

        [[0.8280, 0.0961, 0.0411],
         [0.4277, 0.5055, 0.5884],
         [0.9664, 0.1238, 0.1160]],

        [[0.2624, 0.9480, 0.2103],
         [0.3995, 0.9251, 0.1007],
         [0.0307, 0.0602, 0.1075]]])
torch.Size([3, 3, 3])
3
torch.float32


In [4]:
a = torch.arange(10)
b = torch.ones(10)
c = torch.zeros(10)
print(f"{a = }")
print(f"{b = }")
print(f"{c = }")

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
c = tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [5]:
a = torch.rand(4)
b = torch.rand(5)
# print( a + b) # should give error

In [6]:
a = torch.rand(1_000_000_000)
b = torch.rand(1_000_000_000)

In [7]:
%timeit c = a + b

431 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
!nvidia-smi

Fri Jan 16 07:06:54 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             42W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [9]:
a_gpu = a.to("cuda")
b_gpu = b.to("cuda")
%timeit c_cpu = a_gpu + b_gpu

8.75 ms ± 74.9 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
a = torch.arange(6)
print(a)
print(a.reshape(2,3))
print(a.reshape(3,2))

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [25]:
a = torch.rand(2,3,4)
print(a)

print(a.permute(1,2,0))

tensor([[[0.5193, 0.4860, 0.2569, 0.0931],
         [0.9673, 0.5182, 0.6251, 0.5399],
         [0.7521, 0.8624, 0.3083, 0.7849]],

        [[0.2396, 0.6646, 0.2629, 0.1097],
         [0.2495, 0.9019, 0.9368, 0.5156],
         [0.7345, 0.1387, 0.6086, 0.1036]]])
tensor([[[0.5193, 0.2396],
         [0.4860, 0.6646],
         [0.2569, 0.2629],
         [0.0931, 0.1097]],

        [[0.9673, 0.2495],
         [0.5182, 0.9019],
         [0.6251, 0.9368],
         [0.5399, 0.5156]],

        [[0.7521, 0.7345],
         [0.8624, 0.1387],
         [0.3083, 0.6086],
         [0.7849, 0.1036]]])
